/**
 * Generates a Supabase migration that seeds Fixfy partner contract HTML (v2026).
 * Run: npx tsx scripts/generate-partner-contracts-migration.mts
 *
 * HISTORICAL: this wrote master-os migration 229 (version 2026-06-09) and would
 * overwrite it if run again. Do not re-run; new contract versions are written
 * as new migrations in master-os.
 */
import { writeFileSync } from "fs";
import { join } from "path";
import {
  loadPartnerContractBodyHtml,
  partnerContractTitle,
  PARTNER_CONTRACT_TYPES,
  type PartnerContractType,
} from "../src/lib/contract-template-html.ts";

const VERSION = "2026-06-09";
const outPath = join(
  process.cwd(),
  "../master-os/supabase/migrations/229_partner_fixfy_contract_templates.sql",
);

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

const blocks: string[] = [
  "-- Fixfy partner contract templates (Terms of Use, Self-Billing, Contractor Service Agreement)",
  "-- Generated by master-trade-portal/scripts/generate-partner-contracts-migration.mts",
  "",
  "ALTER TABLE public.contract_versions DROP CONSTRAINT IF EXISTS contract_versions_contract_type_check;",
  "ALTER TABLE public.contract_versions",
  "  ADD CONSTRAINT contract_versions_contract_type_check",
  "  CHECK (contract_type IN (",
  "    'terms_of_use',",
  "    'self_bill_agreement',",
  "    'contractor_service_agreement',",
  "    'workforce_service_agreement',",
  "    'workforce_employment_contract'",
  "  ));",
  "",
];

for (const type of PARTNER_CONTRACT_TYPES) {
  const title = partnerContractTitle(type);
  const body = loadPartnerContractBodyHtml(type);
  blocks.push(`-- ${title}`);
  blocks.push(`UPDATE public.contract_versions SET is_active = false WHERE contract_type = '${type}' AND is_active = true;`);
  blocks.push(
    `INSERT INTO public.contract_versions (contract_type, version, title, body_html, is_active)`,
    `VALUES (`,
    `  '${type}',`,
    `  '${VERSION}',`,
    `  '${sqlEscape(title)}',`,
    `  '${sqlEscape(body)}',`,
    `  true`,
    `);`,
    "",
  );
}

writeFileSync(outPath, blocks.join("\n"), "utf8");
console.log(`Wrote ${outPath}`);
